# configuration information

service:
    default_db_path: "/tmp/tcache"
    default_host: "127.0.0.1"
    default_port: "5200"
    default_databases_num: 16

self_peer:
    host: "127.0.0.1:7001"
    id: "1"

followers:
    - "127.0.0.1:7002"
    - "127.0.0.1:7003"
flowwer_ids:
    - "2"
    - "3"
dir: "/tmp/node"

